name: Simple Workflow own

on:
  push:
    branches:
      ['main']
      pull-request :
      branches :['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print a Message
      run: echo "Hello, GitHub Actions!"
        echo "ferngjier"
