name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Print a Message
      run: echo "Hello, GitHub Actions!"



      name: Artifact Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Package
      run: |
        # Add your build and package commands here
        mkdir dist
        echo "This is a sample artifact file." > dist/sample.txt

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact

    - name: Deploy
      run: |
        # Add your deployment commands here
        cat my-artifact/dist/sample.txt

